<?php

namespace Sociedad\GridBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CabecerasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabecerasRepository extends EntityRepository
{
    public function Cabeceraporusuario($usuarioid=0,$idusuarios=0,$etiqueta="")
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT c,p FROM Sociedad\GridBundle\Entity\Cabeceras c
                                    JOIN c.propiedades p
                                    WHERE c.usuarios_id=:id 
                                    and c.id_usuarios=:idusu
                                    and c.nombre=:etiqueta
                                    ORDER BY c.orden ASC')
                    ->setParameter('id', $usuarioid)
                    ->setParameter('idusu', $idusuarios)
                    ->setParameter('etiqueta', $etiqueta)
                    ->getResult();
                            
    }
    
}