<?php

namespace Sociedad\GridBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropiedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropiedadesRepository extends EntityRepository
{
    public function PropiedadesPorUsuario($usuarioid=0,$idusuarios=0,$etiqueta="")
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p,c FROM Sociedad\GridBundle\Entity\Propiedades p
                                    JOIN p.cabeceras c
                                    WHERE c.usuarios_id=:id 
                                    and c.id_usuarios=:idusu
                                    and c.nombre=:etiqueta
                                    ORDER BY c.orden,p.td ASC')
                    ->setParameter('id', $usuarioid)
                    ->setParameter('idusu', $idusuarios)
                    ->setParameter('etiqueta', $etiqueta)
                    ->getResult();
    }
    
}