<?php

namespace Sociedad\SociosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SociedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactosRepository extends EntityRepository
{
    public function contactosSocio($idsocio,$internetid)
    {
        
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT c FROM  Sociedad\SociosBundle\Entity\Contactos c
                                         WHERE c.socios_id=:id
                                         and c.internetid=:google');
            
        $consulta->setParameter('id', $idsocio);
        $consulta->setParameter('google', $internetid);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    

    
    
}

?>
