<?php

namespace Sociedad\SociosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SociedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactosRepository extends EntityRepository
{
    public function contactosSocio($idsocio,$internetid)
    {
        
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT c FROM  Sociedad\SociosBundle\Entity\Contactos c
                                         WHERE c.socios_id=:id
                                         and c.internetid=:google');
            
        $consulta->setParameter('id', $idsocio);
        $consulta->setParameter('google', $internetid);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    

    public function modificaGoogleId($id=null,$internetid='') {
      $manager=$this->getEntityManager();
      if($id){
          date_default_timezone_set('Europe/Madrid');
          $fechamodi= "'".date(DATE_ATOM, strtotime(date('Y-m-d H:i:s')))."'";
          $internetid="'".$internetid."'";
          $consulta2=$manager->createQuery('update Sociedad\SociosBundle\Entity\Contactos c
                                        SET c.internetid ='.$internetid.', c.fechamodi='.$fechamodi.'
                                        WHERE c.id=:id');
          $consulta2->setParameter('id', $id);
          $consulta2->getResult();
      }
      
    }
    
    
}

?>
