<?php

namespace Sociedad\SociosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SociedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SociosRepository extends EntityRepository
{
}

?>
