imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    
framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig','php'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [MopaBootstrapBundle,SociedadSociedadesBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"

        

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
#Usuarios
fos_user:
    # tipo de ORM/ODB que utilizas (también puede ser 'mongodb', 'couchdb' y 'propel')
    db_driver:     orm
    # el nombre de tu firewall
    firewall_name: main
    # el namespace de tu clase 'User' específica
    user_class:    Sociedad\SociosBundle\Entity\Socios
    registration:
        form:
            type: sociedad_socios_registration    
            handler: sociedad_socios.form.handler.registration            

mopa_bootstrap:
    navbar: ~
    initializr: ~            
   
parameters:
    sociedad.directorio.imagenes: %kernel.root_dir%/../web/bundles/sociedad/uploads/images/    
    sociedad.defecto: 1

fos_facebook:
    file: %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
    alias: facebook
    app_id: 562323857129313
    secret: 6e8c6e55ee1d78dfe404244b4a09173a
    cookie: true
    permissions: [email, user_birthday, user_location]

    