parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: sociedad
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 84cec548c61059ea1fab6eabf2b9c624a
    database_path: null
