<?php

namespace Sociedad\ReservasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MesasPlantasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesasPlantasRepository extends EntityRepository
{
    public function mesasNoReservadasFecha($idsociedad,$fecha,$turno,$plantaid)
    {
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT m FROM Sociedad\ReservasBundle\Entity\MesasPlantas m
                        WHERE m.id NOT IN (SELECT p.mesasplantas_id FROM Sociedad\ReservasBundle\Entity\MesasReservadas p
                        JOIN p.reserva r
                        WHERE r.sociedades_id=:id 
                        and r.fechadesde=:fecha 
                        and r.comida=:turno)
                        and m.plantas_id=:planta');
            
        $consulta->setParameter('id', $idsociedad);
        $consulta->setParameter('fecha', $fecha);
        $consulta->setParameter('turno', $turno);
        $consulta->setParameter('planta', $plantaid);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    
}
