<?php

namespace Sociedad\ReservasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MesasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesasRepository extends EntityRepository
{
    public function mesas($id)
    {
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT m FROM  Sociedad\ReservasBundle\Entity\Mesas m
                                         WHERE m.sociedades_id=:id
                                         ORDER BY m.nombre,m.planta,m.sala');
        $consulta->setParameter('id', $id);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    
}
