<?php

namespace Sociedad\ReservasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservasRepository extends EntityRepository
{
    public function reservaSociedadFecha($idsociedad,$fecha,$turno)
    {
        if($turno){
            $consulta=$this->getEntityManager()
                        ->createQuery('SELECT r FROM  Sociedad\ReservasBundle\Entity\Reservas r
                                             WHERE r.sociedades_id=:id
                                             and r.fechadesde=:fecha
                                             and r.comida=:turno
                                             ORDER BY r.comida');
            
        }else{
            $consulta=$this->getEntityManager()
                        ->createQuery('SELECT r FROM  Sociedad\ReservasBundle\Entity\Reservas r
                                             WHERE r.sociedades_id=:id
                                             and r.fechadesde=:fecha
                                             ORDER BY r.comida');
        }
        $consulta->setParameter('id', $idsociedad);
        $consulta->setParameter('fecha', $fecha);
        if($turno){
            $consulta->setParameter('turno', $turno);        
        }
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    
    public function reservaSocioFecha($idsocio,$fecha,$turno)
    {
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT r FROM  Sociedad\ReservasBundle\Entity\Reservas r
                                         WHERE r.socios_id=:id
                                         and r.fechadesde=:fecha
                                         and r.comida=:turno
                                         ORDER BY r.comida');
            
        $consulta->setParameter('id', $idsocio);
        $consulta->setParameter('fecha', $fecha);
        $consulta->setParameter('turno', $turno);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    
    public function reservaMesasPlantaSocioFecha($idsocio,$fecha,$turno,$plantaid)
    {
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT r,m,p.posx,p.posy FROM  Sociedad\ReservasBundle\Entity\Reservas r
                                         JOIN r.mesasreservadas m
                                         JOIN m.mesaplanta p
                                         WHERE r.socios_id=:id
                                         and r.fechadesde=:fecha
                                         and r.comida=:turno
                                         and p.plantas_id=:planta
                                         ORDER BY r.comida');
            
        $consulta->setParameter('id', $idsocio);
        $consulta->setParameter('fecha', $fecha);
        $consulta->setParameter('turno', $turno);
        $consulta->setParameter('planta', $plantaid);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    
    public function reservaSocioFuturas($idsocio)
    {
        $fecha=date("Y-m-d");
        
        $consulta=$this->getEntityManager()
                    ->createQuery('SELECT r FROM  Sociedad\ReservasBundle\Entity\Reservas r
                                         WHERE r.socios_id=:id
                                         and r.fechadesde>=:fecha
                                         ORDER BY r.fechadesde');
            
        $consulta->setParameter('id', $idsocio);
        $consulta->setParameter('fecha', $fecha);
        $consulta->useResultCache(true, 3600);
        
        return $consulta->getResult();
        
    }    
}
