#!/bin/sh
if [ -x "`dirname "$0"`/node" ]; then
  "`dirname "$0"`/node"  "`dirname "$0"`/./node_modules/less/bin/lessc" "$@"
  ret=$?
else 
  node  "`dirname "$0"`/./node_modules/less/bin/lessc" "$@"
  ret=$?
fi
exit $ret
