<?php

namespace Liip\ThemeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ThemeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Liip\ThemeBundle\Controller\ThemeController();
        return $instance;
    }
}
