<?php

namespace Mopa\Bundle\BootstrapSandboxBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExamplesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Mopa\Bundle\BootstrapSandboxBundle\Controller\ExamplesController();
        return $instance;
    }
}
