<?php

namespace Sociedad\SociedadesBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SociedadesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sociedad\SociedadesBundle\Controller\SociedadesController();
        return $instance;
    }
}
