<?php

namespace Sociedad\ReservasBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MesasController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sociedad\ReservasBundle\Controller\MesasController();
        return $instance;
    }
}
