<?php

namespace Sociedad\GridBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CabecerasController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sociedad\GridBundle\Controller\CabecerasController();
        return $instance;
    }
}
